name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Gradle 6.7
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '6.7'

    - name: Generate Gradle wrapper
      run: gradle wrapper
    - name: Ensure AndroidX is enabled
      run: echo "android.useAndroidX=true" >> gradle.properties
    - name: Commit and push generated wrapper files
      uses: EndBug/add-and-commit@v7
      with:
        message: "Generate Gradle wrapper"
        add: 'gradlew, gradlew.bat, gradle/wrapper/*'
        author_name: 'github-actions'
        author_email: 'github-actions@users.noreply.github.com'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: gradle build