name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    # Step 3: Generate the Gradle wrapper
    - name: Generate Gradle wrapper
      run: gradle wrapper

    # Optional: Commit and push the generated wrapper files
    - name: Commit and push generated wrapper files
      uses: EndBug/add-and-commit@v7
      with:
        message: "Generate Gradle wrapper"
        add: 'gradlew, gradlew.bat, gradle/wrapper/*'
        author_name: 'github-actions'
        author_email: 'github-actions@users.noreply.github.com'